package tablas;
// Generated 7/03/2016 08:24:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Calificaciones generated by hbm2java
 */
@Entity
@Table(name="calificaciones"
    ,schema="public"
)
public class Calificaciones  implements java.io.Serializable {


     private int idUsuario;
     private Double promedio;

    public Calificaciones() {
    }

	
    public Calificaciones(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Calificaciones(int idUsuario, Double promedio) {
       this.idUsuario = idUsuario;
       this.promedio = promedio;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="promedio", precision=17, scale=17)
    public Double getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(Double promedio) {
        this.promedio = promedio;
    }




}


