package modelo;
// Generated 7/03/2016 08:24:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String correoUsuario;
     private String contraseniaUsuario;

    public Usuario() {
    }

    public Usuario(int idUsuario, String correoUsuario, String contraseniaUsuario) {
       this.idUsuario = idUsuario;
       this.correoUsuario = correoUsuario;
       this.contraseniaUsuario = contraseniaUsuario;
    }
   
     @Id 

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="correo_usuario", nullable=false, length=200)
    public String getCorreoUsuario() {
        return this.correoUsuario;
    }
    
    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }

    
    @Column(name="contrasenia_usuario", nullable=false, length=200)
    public String getContraseniaUsuario() {
        return this.contraseniaUsuario;
    }
    
    public void setContraseniaUsuario(String contraseniaUsuario) {
        this.contraseniaUsuario = contraseniaUsuario;
    }




}


